name: opencloset_sync
description: Optional cloud synchronization for OpenCloset.

version: 0.0.1
homepage: https://github.com/sophie-nayebi/OpenCloset

publish_to: "none"

repository: https://github.com/sophie-nayebi/OpenCloset/tree/main/packages/sync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  http: ^1.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test: { sdk: flutter }
